name: Build Image and Deploy to cluster

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Login to repository
      run: docker login ${{secrets.DOCKER_ENDPOINT}} -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
      
    - name: Build the Docker image
      run: docker build --pull -f Dockerfile . -t ${{secrets.DOCKER_ENDPOINT}}/zero-tools/ayelet-lol-dice:latest

    - name: Push image
      run: docker push ${{secrets.DOCKER_ENDPOINT}}/zero-tools/ayelet-lol-dice:latest
